name: Build

on: push

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm ci
    - name: Create google-services.json 
      env: 
        FIREBASE_SECRET: ${{ secrets.FIREBASE_SECRET }}
      run: echo $FIREBASE_SECRET > android/app/google-services.json
    - name: Decode Keystore
      uses: timheuer/base64-to-file@v1
      with:
        fileName: 'android/app/keystore.jks'
        encodedString: ${{ secrets.KEYSTORE }}
    - name: Build APK
      env:
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
      run:  |
        cd android && 
        ls -l app/
        chmod +x gradlew && 
        ./gradlew assembleRelease
    - name: Create Sentry release
      uses: getsentry/action-release@v1
      env:
        SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
        SENTRY_PROJECT: hanji
        VERSION_CODE: $(grep -o "versionCode\s\+.*" app/build.gradle | awk '{print $2}')
        VERSION_NAME: $(grep "versionName" app/build.gradle | awk '{print $2}' | tr -d \''"\')
      with:
        environment: production
        version: com.a494studios.koreanconjugator@${{ env.VERSION_NAME }}+${{ env.VERSION_CODE }}
        sourcemaps: android/app/build/generated/assets/react/release/index.android.bundle android/app/build/generated/sourcemaps/react/release/index.android.bundle.map
        strip_common_prefix: true
    - name: Upload APK
      uses: actions/upload-artifact@v1
      with:
        name: app-release.apk
        path: android/app/build/outputs/apk/release/