name: Build

on: push

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm ci
    - name: Create google-services.json 
      env: 
        FIREBASE_SECRET: ${{ secrets.FIREBASE_SECRET }}
      run: echo $FIREBASE_SECRET > android/app/google-services.json
    - name: Decode Keystore
      run: echo $ENCODED_STRING | base64 -di > android/app/keystore.jks
      env:
        ENCODED_STRING: ${{ secrets.KEYSTORE }}
    - name: Build APK
      env:
          SERVER_URL: ${{ secrets.SERVER_URL }}
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
      run:  |
        cd android && 
        chmod +x gradlew && 
        ./gradlew assembleRelease
    - id: get_version
      run: |
        echo "::set-output name=VERSION_CODE::$(grep -o "versionCode\s\+.*" android/app/build.gradle | awk '{print $2}')" &&
        echo "::set-output name=VERSION_NAME::$(grep "versionName" android/app/build.gradle | awk '{print $2}' | tr -d \''"\')"
    - name: Create Sentry release
      uses: getsentry/action-release@v1
      env:
        SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
        SENTRY_PROJECT: hanji
        VERSION_CODE: ${{ steps.get_version.outputs.VERSION_CODE }}
        VERSION_NAME: ${{ steps.get_version.outputs.VERSION_NAME }}
      with:
        environment: production
        version: com.a494studios.koreanconjugator@${{ env.VERSION_NAME }}+${{ env.VERSION_CODE }}
        sourcemaps: android/app/build/generated/assets/react/release/index.android.bundle android/app/build/generated/sourcemaps/react/release/index.android.bundle.map
    - name: Upload APK
      uses: actions/upload-artifact@v1
      with:
        name: app-release.apk
        path: android/app/build/outputs/apk/release/